### PR TITLE
Fix build failure

### PR DESCRIPTION
**Pull request by haennes**
Seems to be related to this issue nix-community/naersk#323

### CODE REVIEW

**Review by zvolin — APPROVED** [review]
thanks :+1: I changed base to my branch but in case you want that in master let me know

**Comment by haennes** [comment]
Thats fine :)
I will bump the your PR in the upstream as well, hopefully it will be merged eventually.

**Comment by zvolin** [comment]
Since I merged to the branch of that PR it should already be there

**Comment by zvolin** [comment]
Ah I guess I misunderstood :) yeah go for it, thanks

**Comment by haennes** [comment]
Additional question, I would like to confirm, that this is broken on the nix-community upstream, any Idea on how to do that?

**Comment by zvolin** [comment]
Do you mean to confirm that manix doesn't provide home-manager options?

**Comment by haennes** [comment]
No, i only got this build failure when (for example) doing nix run on this fork, if I do it on the nix-community/manix i dont get a failure. So I cant confirm my commit actually fixes a bug in the upstream.
I want to confirm that before giving another bump to the upstream PR.
Hope this makes it clear :)

**Comment by zvolin** [comment]
Interesting, I don't know. The only change I think could make a difference is

```
  release ? "24.05",
```

In upstream they have 23.05. my only guess is try changing only this in upstream and rebuild then

**Comment by haennes** [comment]
Just tried that, even when committing this doesn´t break the build.
Did you encounter a build-failure as well before you merged this?

**Comment by zvolin** [comment]
Nope, but I did this change quite some time ago, didn't try to build this since then

**Pull request merged**
